# Generated by Django 4.0.4 on 2024-07-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nombre_producto_producto_nombreproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CREADA', 'Creada'), ('REACTIFICADA', 'Rectificada'), ('POR_ENTREGAR', 'Por Entregar'), ('ENTREGADA', 'Entregada'), ('RECHAZADA', 'Rechazada')], default='CREADA', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('direccion_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('rut_receptor', models.CharField(blank=True, max_length=10, null=True)),
                ('foto_entrega', models.ImageField(blank=True, null=True, upload_to='fotos_entrega/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
