# Generated by Django 4.0.4 on 2024-07-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='nombreProducto',
        ),
    ]
